src/Entity/Candidature.php
<?php

namespace App\Entity;

use App\Repository\CandidatureRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CandidatureRepository::class)]
class Candidature
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nomC = null;

    #[ORM\Column(length: 255)]
    private ?string $prenomC = null;

    #[ORM\Column(length: 255)]
    private ?string $emailC = null;

    #[ORM\Column(type: Types::BINARY)]
    private $CV_c = null;

    #[ORM\Column(type: Types::BINARY)]
    private $motivation_letter = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomC(): ?string
    {
        return $this->nomC;
    }

    public function setNomC(string $nomC): static
    {
        $this->nomC = $nomC;

        return $this;
    }

    public function getPrenomC(): ?string
    {
        return $this->prenomC;
    }

    public function setPrenomC(string $prenomC): static
    {
        $this->prenomC = $prenomC;

        return $this;
    }

    public function getEmailC(): ?string
    {
        return $this->emailC;
    }

    public function setEmailC(string $emailC): static
    {
        $this->emailC = $emailC;

        return $this;
    }

    public function getCVC()
    {
        return $this->CV_c;
    }

    public function setCVC($CV_c): static
    {
        $this->CV_c = $CV_c;

        return $this;
    }

    public function getMotivationLetter()
    {
        return $this->motivation_letter;
    }

    public function setMotivationLetter($motivation_letter): static
    {
        $this->motivation_letter = $motivation_letter;

        return $this;
    }
}

src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
class Offre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 3, max: 15)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 5, max: 240)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $societe = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $adresse_societe = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Email]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $type_offre = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $qualification = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $comptence = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank]
    #[Assert\GreaterThan("now")]
    private ?\DateTimeInterface $deadline = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getSociete(): ?string
    {
        return $this->societe;
    }

    public function setSociete(string $societe): static
    {
        $this->societe = $societe;

        return $this;
    }

    public function getAdresseSociete(): ?string
    {
        return $this->adresse_societe;
    }

    public function setAdresseSociete(string $adresse_societe): static
    {
        $this->adresse_societe = $adresse_societe;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTypeOffre(): ?string
    {
        return $this->type_offre;
    }

    public function setTypeOffre(string $type_offre): static
    {
        $this->type_offre = $type_offre;

        return $this;
    }

    public function getQualification(): ?string
    {
        return $this->qualification;
    }

    public function setQualification(string $qualification): static
    {
        $this->qualification = $qualification;

        return $this;
    }

    public function getComptence(): ?string
    {
        return $this->comptence;
    }

    public function setComptence(string $comptence): static
    {
        $this->comptence = $comptence;

        return $this;
    }

    public function getDeadline(): ?\DateTimeInterface
    {
        return $this->deadline;
    }

    public function setDeadline(\DateTimeInterface $deadline): static
    {
        $this->deadline = $deadline;

        return $this;
    }
}

src/Form/OffreType.php
<?php

namespace App\Form;

use App\Entity\Offre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType; 
use Symfony\Component\Form\Extension\Core\Type\EmailType; 
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class OffreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('description', TextareaType::class, [
                'label' => 'Description',
                'required' => true,
                'attr' => ['rows' => 3], 
                'constraints' => [
                    new Assert\NotBlank(),
                    new Assert\Length(['min' => 5, 'max' => 240]),
                ],
            ])
            ->add('societe')
            ->add('adresse_societe')
            ->add('email', EmailType::class, [ 
                'label' => 'Email',
                'required' => true,
                'constraints' => [
                    new Assert\NotBlank(),
                    new Assert\Email(),
                ],
            ])
            ->add('type_offre')
            ->add('qualification', ChoiceType::class, [
                'label' => 'Qualification',
                'choices' => [
                    'Baccalaureat' => 'Baccalaureat',
                    'Licence en informatique' => 'Licence en informatique',
                    'Master en informatique' => 'Master en informatique',
                    'Cycle ingenieur termine' => 'Cycle ingenieur termine',
                    'Certifications' => 'Certifications',
                    // Add other qualification options
                ],
                'multiple' => false, // Passage de 'true' à 'false' pour en faire une liste déroulante
                'expanded' => false, // Passage de 'true' à 'false'
            ])
            ->add('comptence', ChoiceType::class, [
                'label' => 'Compétence',
                'choices' => [
                    'Web Development' => 'Web Development',
                    'Backend Development' => 'Backend Development',
                    'Frontend Development' => 'Frontend Development',
                    'Mobile App Development' => 'Mobile App Development',
                    'Database Management' => 'Database Management',
                    'Data Analysis' => 'Data Analysis',
                    'AI and Machine Learning' => 'AI and Machine Learning',
                    'Cybersecurity' => 'Cybersecurity',
                    'Cloud Computing' => 'Cloud Computing',
                    'DevOps' => 'DevOps',
                    'Network Administration' => 'Network Administration',
                    'UI/UX Design' => 'UI/UX Design',
                    'Quality Assurance' => 'Quality Assurance',
                    'Software Testing' => 'Software Testing',
                    'Agile Methodologies' => 'Agile Methodologies',
                    'Project Management' => 'Project Management',
                    'Embedded Systems' => 'Embedded Systems',
                    'Robotics' => 'Robotics',
                    
                ],
                'multiple' => false, // Passage de 'true' à 'false'
                'expanded' => false, // Passage de 'true' à 'false'
            ])
            ->add('deadline')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Offre::class,
        ]);
    }
}

src/Controller/OffreController.php
<?php

namespace App\Controller;

use App\Entity\Offre;
use App\Form\OffreType;
use App\Repository\OffreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/offre')]
class OffreController extends AbstractController
{
    #[Route('/', name: 'app_offre_index', methods: ['GET'])]
    public function index(OffreRepository $offreRepository): Response
    {
        return $this->render('offre/index.html.twig', [
            'offres' => $offreRepository->findAll(),
        ]);
    }

    #[Route('/index', name: 'front_index', methods: ['GET'])]
    public function indexfront(OffreRepository $offreRepository): Response
    {
        return $this->render('offre/offrefront.html.twig', [
            'offres' => $offreRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_offre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $offre = new Offre();
        $form = $this->createForm(OffreType::class, $offre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($offre);
            $entityManager->flush();

            return $this->redirectToRoute('app_offre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('offre/new.html.twig', [
            'offre' => $offre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_offre_show', methods: ['GET'])]
    public function show(Offre $offre): Response
    {
        return $this->render('offre/show.html.twig', [
            'offre' => $offre,
        ]);
    }

    #[Route('/{id}', name: 'postuler', methods: ['GET'])]
    public function postuler(Offre $offre): Response
    {
        return $this->render('offre/postuler.html.twig', [
            'offre' => $offre,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_offre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Offre $offre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(OffreType::class, $offre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_offre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('offre/edit.html.twig', [
            'offre' => $offre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_offre_delete', methods: ['POST'])]
    public function delete(Request $request, Offre $offre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$offre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($offre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_offre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/offre/_delete_form.html.twig
<form method="post" action="{{ path('app_offre_delete', {'id': offre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ offre.id) }}">
    <button type="button" class="btn btn-outline-danger">Delete</button>
</form>

templates/offre/_form.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}



<!DOCTYPE html>
<html>
<head>
    <title> offre </title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .form-container {
            width: 500px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
        }
        .form-container label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        .form-container input[type="text"],
        .form-container input[type="date"],
        .form-container textarea {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }
        .form-container button {
            padding: 10px 15px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }
        .form-container button:hover {
            background-color: #0056b3;
        }
        .error-message {
            color: red;
            font-size: 14px;
            margin-top: 5px;
        }
    </style>
</head>
<body>
    <div class="form-container">
    
        
        {{ form_start(form) }}
        
        {{ form_label(form.titre) }}
        {{ form_widget(form.titre) }}
        {{ form_errors(form.titre) }}

        {{ form_label(form.description) }}
        {{ form_widget(form.description) }}
        {{ form_errors(form.description) }}

        {{ form_label(form.societe) }}
        {{ form_widget(form.societe) }}
        {{ form_errors(form.societe) }}

        {{ form_label(form.adresse_societe) }}
        {{ form_widget(form.adresse_societe) }}
        {{ form_errors(form.adresse_societe) }}

        {{ form_label(form.email) }}
        {{ form_widget(form.email) }}
        {{ form_errors(form.email) }}

        {{ form_label(form.type_offre) }}
        {{ form_widget(form.type_offre) }}
        {{ form_errors(form.type_offre) }}

        {{ form_label(form.qualification) }}
        {{ form_widget(form.qualification) }}
        {{ form_errors(form.qualification) }}

        {{ form_label(form.comptence) }}
        {{ form_widget(form.comptence) }}
        {{ form_errors(form.comptence) }}


        {{ form_label(form.deadline) }}
        {{ form_widget(form.deadline) }}
        {{ form_errors(form.deadline) }}
        <br>

        <button type="submit" style="margin-left: 180px;" class="btn">{{ button_label|default('Save') }}</button>
        
        {{ form_end(form) }}
    </div>
</body>
</html>

templates/offre/candidature_form.html.twig
{# templates/candidature/candidature_form.html.twig #}
{% extends 'base.html.twig' %}

{% block title %}Apply for a Job{% endblock %}

{% block body %}
    <h1>Apply for a Job</h1>

    {{ form_start(form) }}
    <div class="form-group">
        {{ form_label(form.cv, 'CV') }}
        {{ form_widget(form.cv, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.cv) }}
    </div>

    <div class="form-group">
        {{ form_label(form.motivationLetter, 'Motivation Letter') }}
        {{ form_widget(form.motivationLetter, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.motivationLetter) }}
    </div>

    <button type="submit" class="btn btn-primary">Apply</button>
    {{ form_end(form) }}
{% endblock %}

templates/offre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}edit Offre {% endblock %}

    {% block content1 %}
        <ul id="sidebarnav">
          <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">Accueil</span>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link" href="{{path('accueil')}}" aria-expanded="false">
              <span>
                <i class="ti ti-layout-dashboard"></i>
              </span>
              <span class="hide-menu">accueil</span>
            </a>
          </li>
          <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu"> Tables</span>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link" href="{{path('app_offre_index')}}" aria-expanded="false">
              <span>
                <i class="ti ti-article"></i>
              </span>
              <span class="hide-menu">Offres</span>
            </a>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link" href="{{path('app_events_dash')}}" aria-expanded="false">
              <span>
                <i class="ti ti-alert-circle"></i>
              </span>
              <span class="hide-menu">Events</span>
            </a>
          </li>
      
    <h1>Edit Offre</h1>

    {{ include('offre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_offre_index') }}">back to list</a>

    {{ include('offre/_delete_form.html.twig') }}
{% endblock %}

templates/offre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offre {% endblock %}

    {% block content1 %}
    

    <h1 style="margin-bottom: 15px; margin-left: 340px;">Liste des Offres </h1>
    <br>
        <br><br>
        <br>


        <div class="form-container">
  
        <button type="button" class="btn btn-outline-primary">
            <a href="{{ path('app_offre_new') }}" style="color: primary;">ajouter</a>
        </button>
    </div>


        {# <a href="{{ path('app_offre_new') }}">new</a> #}
        <br><br>
      
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Titre</th>
                <th>Description</th>
                <th>Societe</th>
                <th>Adresse_societe</th>
                <th>Email</th>
                <th>Type offre</th>
                <th>Qualification</th>
                <th>Comptence</th>
                <th>Deadline</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for offre in offres %}
            <tr>
                <td>{{ offre.titre }}</td>
                <td>{{ offre.description }}</td>
                <td>{{ offre.societe }}</td>
                <td>{{ offre.adresseSociete }}</td>
                <td>{{ offre.email }}</td>
                <td>{{ offre.typeOffre }}</td>
                <td>{{ offre.qualification }}</td>
                <td>{{ offre.comptence }}</td>
                <td>{{ offre.deadline ? offre.deadline|date('Y-m-d') : '' }}</td>
                <td>
                  <button type="button" class="btn btn-outline-info">
                    <a href="{{ path('app_offre_show', {'id': offre.id}) }}" style="color: info; ">afficher</a>
                </button>
                <button type="button" class="btn btn-outline-success">
                    <a href="{{ path('app_offre_edit', {'id': offre.id}) }}" style="color: green;">modifier</a>
                </button>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/offre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}new Offre {% endblock %}

    {% block content1 %}
        <ul id="sidebarnav">
          <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">Accueil</span>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link" href="{{path('accueil')}}" aria-expanded="false">
              <span>
                <i class="ti ti-layout-dashboard"></i>
              </span>
              <span class="hide-menu">accueil</span>
            </a>
          </li>
          <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu"> Tables</span>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link" href="{{path('app_offre_index')}}" aria-expanded="false">
              <span>
                <i class="ti ti-article"></i>
              </span>
              <span class="hide-menu">Offres</span>
            </a>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link" href="{{path('app_events_dash')}}" aria-expanded="false">
              <span>
                <i class="ti ti-alert-circle"></i>
              </span>
              <span class="hide-menu">Events</span>
            </a>
          </li>
      





    <h1 style="margin-left: 420px; margin-bottom: 50px;" >ajouter un Offre</h1>
    <br>

    {{ include('offre/_form.html.twig') }}

    <br>

    <br>

    <br>
    <br>

    <a href="{{ path('app_offre_index') }}">back to list</a>
{% endblock %}

templates/offre/offrefront.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events{% endblock %}

{% block content1 %}

 <body className='snippet-body'>      

    <!-- HOME -->
   <section class="home-section section-hero overlay bg-image" style="background-image: url('images/hero_1.jpg'); height: 1200px; padding-top: 100px; padding-bottom: 100px;" id="home-section">


      <div class="container">
        <div class="row align-items-center justify-content-center">

    <h1>Liste des Offres </h1>
    <br>
        <br><br>
        <br>
        

   
        <br><br>
      
    <table class="table table-dark">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Description</th>
                <th>Societe</th>
                <th>Adresse_societe</th>
                <th>Email</th>
                <th>Type </th>
                <th>Qualification</th>
                <th>Comptence</th>
                <th>Deadline</th>
                <th>actions</th>

             
            </tr>
        </thead>
        <tbody>
        {% for offre in offres %}
            <tr>
                <td>{{ offre.titre }}</td>
                <td>{{ offre.description }}</td>
                <td>{{ offre.societe }}</td>
                <td>{{ offre.adresseSociete }}</td>
                <td>{{ offre.email }}</td>
                <td>{{ offre.typeOffre }}</td>
                <td>{{ offre.qualification }}</td>
                <td>{{ offre.comptence }}</td>
                <td>{{ offre.deadline ? offre.deadline|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('postuler', {'id': offre.id}) }}">postuler</a>
                   
                </td>
                <td>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>



  </body>


{% endblock %}

templates/offre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offre {% endblock %}

    {% block content1 %}
    
    <h1 style="margin-bottom: 15px; margin-left: 400px;">Offre</h1>

    <table class="table" style="margin-top: 20px;">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ offre.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ offre.titre }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ offre.description }}</td>
            </tr>
            <tr>
                <th>Societe</th>
                <td>{{ offre.societe }}</td>
            </tr>
            <tr>
                <th>Adresse_societe</th>
                <td>{{ offre.adresseSociete }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ offre.email }}</td>
            </tr>
            <tr>
                <th>Type_offre</th>
                <td>{{ offre.typeOffre }}</td>
            </tr>
            <tr>
                <th>Qualification</th>
                <td>{{ offre.qualification }}</td>
            </tr>
            <tr>
                <th>Comptence</th>
                <td>{{ offre.comptence }}</td>
            </tr>
            <tr>
                <th>Deadline</th>
                <td>{{ offre.deadline ? offre.deadline|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>






    <div class="container mt-4" >
      <div class="row">
          <div class="col-md-6">
              <button type="button" class="btn btn-outline-success">
                  <a href="{{ path('app_offre_edit', {'id': offre.id}) }}" style="color: green;">Edit</a>
              </button>
          </div>
          <div class="col-md-6 text-md-right">
              <a href="{{ path('app_offre_index') }}" class="btn btn-link">Back to List</a>
          </div>
      </div>

      <hr class="my-4">

      <div class="row">
          <div class="col-md-12">
            {{ include('offre/_delete_form.html.twig') }}
          </div>
      </div>
  </div>
{% endblock %}